### ISSUE TITLE
Optimize Enable Data Preview

### ISSUE THREAD

**Issue by sebllll** [vvvv/VL.IO.OSC#1]
![image](https://user-images.githubusercontent.com/646501/102609264-7b1f9a80-412b-11eb-86c2-46317e8a69cd.png)
like so, that more nodes are in the if?

**Comment by sebllll** [comment]
just because most of the time you don't need it and then it takes no computation time...

**Comment by joreg** [comment]
my thinking here somehow was that i'd still want to collect the messages for preview, while the preview is off, so that when you turn it on, you get the full preview..but i agree, seems overdone. fixed as proposed.
